import type { Metadata } from "next";

import { SUIT } from "./fontFace";

import "@/app/ui/styles/global.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={SUIT.className}>{children}</body>
    </html>
  );
}
