name: "Test Coverage Report"
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          threshold: 80
