name: "Test Coverage Report"
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write

    steps:
      - name: Run tests and collect coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          package-manager: pnpm
          threshold: 80
